mountainInfos=[
  {"name":"利尻岳","area":"北海道", "altitude":"1719m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"羅臼岳","area":"北海道", "altitude":"1661m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"斜里岳","area":"北海道", "altitude":"1547m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"阿寒岳","area":"北海道", "altitude":"1499m", "difficulty":"★", "fitnessLevel":"★"},
  {"name":"大雪山","area":"北海道", "altitude":"2290m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"トムラウシ山","area":"北海道", "altitude":"2141m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"十勝岳","area":"北海道", "altitude":"2077m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"後方羊蹄山","area":"北海道", "altitude":"1893m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"岩木山","area":"東北", "altitude":"1625m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"八甲田山","area":"東北", "altitude":"1585m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"八幡平","area":"東北", "altitude":"1613m", "difficulty":"★", "fitnessLevel":"★"},
  {"name":"岩手山","area":"東北", "altitude":"2038m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"早池峰山","area":"東北", "altitude":"1917m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"鳥海山","area":"東北", "altitude":"2236m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"月山","area":"東北", "altitude":"1980m", "difficulty":"★★", "fitnessLevel":"★"},
  {"name":"蔵王山","area":"東北", "altitude":"1841m", "difficulty":"★", "fitnessLevel":"★"},
  {"name":"吾妻山","area":"東北", "altitude":"2035m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"安達太良山","area":"東北", "altitude":"1700m", "difficulty":"★★", "fitnessLevel":"★"},
  {"name":"磐梯山","area":"東北", "altitude":"1819m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"会津駒ヶ岳","area":"東北", "altitude":"2132m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"那須岳","area":"北関東", "altitude":"1915m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"燧ヶ岳","area":"尾瀬", "altitude":"2356m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"至仏山","area":"尾瀬", "altitude":"2228m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"武尊山","area":"上州", "altitude":"2158m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"赤城山","area":"上州", "altitude":"1828m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"皇海山","area":"足尾", "altitude":"2144m", "difficulty":"★★", "fitnessLevel":"★"},
  {"name":"越後駒ヶ岳","area":"上信越", "altitude":"2003m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"平ヶ岳","area":"上信越", "altitude":"2141m", "difficulty":"★", "fitnessLevel":"★★★"},
  {"name":"巻機山","area":"上信越", "altitude":"1967m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"谷川岳","area":"上信越", "altitude":"1963m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"雨飾山","area":"上信越", "altitude":"1963m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"妙高山","area":"上信越", "altitude":"2454m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"火打山","area":"上信越", "altitude":"2462m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"高妻山","area":"上信越", "altitude":"2353m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"草津白根山","area":"上信越", "altitude":"2165m", "difficulty":"★", "fitnessLevel":"★"},
  {"name":"浅間山","area":"上信越", "altitude":"2568m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"両神山","area":"秩父", "altitude":"1723m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"天城山","area":"南関東", "altitude":"1406m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"白馬岳","area":"北アルプス", "altitude":"2932m", "difficulty":"★★★", "fitnessLevel":"★★★"},
  {"name":"剱岳","area":"北アルプス", "altitude":"2999m", "difficulty":"★★★", "fitnessLevel":"★★★"},
  {"name":"立山","area":"北アルプス", "altitude":"3015m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"薬師岳","area":"北アルプス", "altitude":"2926m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"常念岳","area":"北アルプス", "altitude":"2857m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"笠ヶ岳","area":"北アルプス", "altitude":"2897m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"焼岳","area":"北アルプス", "altitude":"2444m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"乗鞍岳","area":"北アルプス", "altitude":"3026m", "difficulty":"★", "fitnessLevel":"★"},
  {"name":"美ヶ原","area":"美ヶ原", "altitude":"2034m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"霧ヶ峰","area":"霧ヶ峰", "altitude":"1925m", "difficulty":"★", "fitnessLevel":"★"},
  {"name":"八ヶ岳","area":"八ヶ岳", "altitude":"2899m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"御嶽山","area":"御嶽山", "altitude":"3067m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"木曽駒ヶ岳","area":"中央アルプス", "altitude":"2956m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"空木岳","area":"中央アルプス", "altitude":"2864m", "difficulty":"★★★", "fitnessLevel":"★★★"},
  {"name":"恵那山","area":"中央アルプス", "altitude":"2191m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"甲斐駒ヶ岳","area":"南アルプス", "altitude":"2967m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"仙丈ヶ岳","area":"南アルプス", "altitude":"3033m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"白山","area":"北陸", "altitude":"2702m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"荒島岳","area":"北陸", "altitude":"1524m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"伊吹山","area":"近畿", "altitude":"1377m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"大台ヶ原山","area":"近畿", "altitude":"1695m", "difficulty":"★", "fitnessLevel":"★"},
  {"name":"大峰山","area":"近畿", "altitude":"1915m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"大山","area":"中国", "altitude":"1709m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"石鎚山","area":"四国", "altitude":"1982m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"九重山","area":"九州", "altitude":"1787m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"祖母山","area":"九州", "altitude":"1756m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"阿蘇山","area":"九州", "altitude":"1592m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"霧島山","area":"九州", "altitude":"1700m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"開聞岳","area":"九州", "altitude":"922m", "difficulty":"★", "fitnessLevel":"★"},
  {"name":"ニセイカウシュッペ山","area":"北海道", "altitude":"1883m", "difficulty":"★★", "fitnessLevel":"22"},
  {"name":"オプタテシケ山","area":"北海道", "altitude":"2013m", "difficulty":"★★★★", "fitnessLevel":"44"},
  {"name":"神威岳","area":"北海道", "altitude":"1600m", "difficulty":"★★★★", "fitnessLevel":"41"},
  {"name":"余市岳","area":"北海道", "altitude":"1488m", "difficulty":"★★", "fitnessLevel":"30"},
  {"name":"ニセコアンヌプリ","area":"北海道", "altitude":"1308m", "difficulty":"★", "fitnessLevel":"14"},
  {"name":"狩場山","area":"北海道", "altitude":"1520m", "difficulty":"★★", "fitnessLevel":"22"},
  {"name":"大千軒岳","area":"北海道", "altitude":"1072m", "difficulty":"★★", "fitnessLevel":"28"},
  {"name":"五葉山","area":"東北", "altitude":"1351m", "difficulty":"★", "fitnessLevel":"17"},
  {"name":"乳頭山（烏帽子岳）","area":"東北", "altitude":"1478m", "difficulty":"★★", "fitnessLevel":"20"},
  {"name":"太平山","area":"東北", "altitude":"1170m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"泉ヶ岳","area":"東北", "altitude":"1175m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"摩耶山","area":"東北", "altitude":"1020m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"祝瓶山","area":"東北", "altitude":"1417m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"一切経山","area":"東北", "altitude":"1949m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"大滝根山","area":"東北", "altitude":"1192m", "difficulty":"★", "fitnessLevel":"-"},
  {"name":"二岐山","area":"東北", "altitude":"1544m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"七ヶ岳","area":"東北", "altitude":"1636m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"荒海山（太郎岳）","area":"東北", "altitude":"1581m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"八溝山","area":"関東", "altitude":"1022m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"男鹿岳","area":"関東", "altitude":"1777m", "difficulty":"★★★★", "fitnessLevel":"-"},
  {"name":"高原山","area":"関東", "altitude":"1795m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"太郎山","area":"関東", "altitude":"2368m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"袈裟丸山","area":"関東", "altitude":"1961m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"景鶴山","area":"関東", "altitude":"2004m", "difficulty":"登山不可", "fitnessLevel":"登山不可"},
  {"name":"朝日岳","area":"関東", "altitude":"1945m", "difficulty":"★★★★", "fitnessLevel":"-"},
  {"name":"諏訪山","area":"関東", "altitude":"1549m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"三頭山","area":"関東", "altitude":"1531m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"大山","area":"関東", "altitude":"1252m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"金時山","area":"関東", "altitude":"1212m", "difficulty":"★", "fitnessLevel":"-"},
  {"name":"箱根山（神山）","area":"関東", "altitude":"1438m", "difficulty":"★", "fitnessLevel":"-"},
  {"name":"金北山","area":"甲信越", "altitude":"1172m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"粟ヶ岳","area":"甲信越", "altitude":"1293m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"浅草岳","area":"甲信越", "altitude":"1585m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"米山","area":"甲信越", "altitude":"993m", "difficulty":"★", "fitnessLevel":"-"},
  {"name":"横手山","area":"甲信越", "altitude":"2307m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"笠ヶ岳","area":"甲信越", "altitude":"2076m", "difficulty":"★", "fitnessLevel":"-"},
  {"name":"斑尾山","area":"甲信越", "altitude":"1382m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"焼山","area":"甲信越", "altitude":"2400m", "difficulty":"★★★★", "fitnessLevel":"-"},
  {"name":"黒姫山","area":"甲信越", "altitude":"1221m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"鉢伏山","area":"甲信越", "altitude":"1929m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"入笠山","area":"甲信越", "altitude":"1955m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"国師ヶ岳","area":"甲信越", "altitude":"2592m", "difficulty":"★", "fitnessLevel":"-"},
  {"name":"黒岳（御坂黒岳）","area":"甲信越", "altitude":"1793m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"朝日岳","area":"北・中央アルプス", "altitude":"2418m", "difficulty":"★★★★", "fitnessLevel":"-"},
  {"name":"唐松岳","area":"北・中央アルプス", "altitude":"2696m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"爺ヶ岳","area":"北・中央アルプス", "altitude":"2670m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"蓮華岳","area":"北・中央アルプス", "altitude":"2799m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"鍬崎山","area":"北・中央アルプス", "altitude":"2090m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"野口五郎岳","area":"北・中央アルプス", "altitude":"2924m", "difficulty":"★★★★", "fitnessLevel":"-"},
  {"name":"三俣蓮華岳","area":"北・中央アルプス", "altitude":"2841m", "difficulty":"★★★★", "fitnessLevel":"-"},
  {"name":"鉢盛山","area":"北・中央アルプス", "altitude":"2447m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"越百山","area":"北・中央アルプス", "altitude":"2614m", "difficulty":"★★★★", "fitnessLevel":"-"},
  {"name":"南木曽岳","area":"北・中央アルプス", "altitude":"1679m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"奥三界岳","area":"北・中央アルプス", "altitude":"1811m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"アサヨ峰","area":"南アルプス", "altitude":"2799m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"奥茶臼山","area":"南アルプス", "altitude":"2474m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"茶臼岳","area":"南アルプス", "altitude":"2604m", "difficulty":"★★★★", "fitnessLevel":"-"},
  {"name":"山伏","area":"東海・北陸", "altitude":"2013m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"黒法師岳","area":"東海・北陸", "altitude":"2068m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"高塚山","area":"東海・北陸", "altitude":"1621m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"熊伏山","area":"東海・北陸", "altitude":"1654m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"白木峰","area":"東海・北陸", "altitude":"1596m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"人形山","area":"東海・北陸", "altitude":"1726m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"猿ヶ馬場山","area":"東海・北陸", "altitude":"1875m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"川上岳","area":"東海・北陸", "altitude":"1625m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"鷲ヶ岳","area":"東海・北陸", "altitude":"1671m", "difficulty":"★", "fitnessLevel":"-"},
  {"name":"医王山","area":"東海・北陸", "altitude":"939m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"大門山","area":"東海・北陸", "altitude":"1572m", "difficulty":"★", "fitnessLevel":"-"},
  {"name":"大笠山","area":"東海・北陸", "altitude":"1822m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"三方岩岳","area":"東海・北陸", "altitude":"1736m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"野伏ヶ岳","area":"東海・北陸", "altitude":"1674m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"経ヶ岳","area":"東海・北陸", "altitude":"1625m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"冠山","area":"東海・北陸", "altitude":"1257m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"藤原岳","area":"近畿", "altitude":"1140m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"倶留尊山","area":"近畿", "altitude":"1037m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"三峰山","area":"近畿", "altitude":"1235m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"高見山","area":"近畿", "altitude":"1248m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"龍門岳","area":"近畿", "altitude":"904m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"山上ヶ岳","area":"近畿", "altitude":"1719m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"護摩壇山","area":"近畿", "altitude":"1372m", "difficulty":"★", "fitnessLevel":"-"},
  {"name":"大和葛城山","area":"近畿", "altitude":"959m", "difficulty":"★", "fitnessLevel":"-"},
  {"name":"蓬莱山","area":"近畿", "altitude":"1174m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"比叡山","area":"近畿", "altitude":"848m", "difficulty":"★", "fitnessLevel":"-"},
  {"name":"愛宕山","area":"近畿", "altitude":"924m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"六甲山","area":"近畿", "altitude":"931m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"扇ノ山","area":"中国・四国", "altitude":"1310m", "difficulty":"★", "fitnessLevel":"-"},
  {"name":"那岐山","area":"中国・四国", "altitude":"1255m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"道後山","area":"中国・四国", "altitude":"1271m", "difficulty":"★", "fitnessLevel":"-"},
  {"name":"吾妻山","area":"中国・四国", "altitude":"1238m", "difficulty":"★", "fitnessLevel":"-"},
  {"name":"伊予富士","area":"中国・四国", "altitude":"1756m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"瓶ヶ森","area":"中国・四国", "altitude":"1897m", "difficulty":"★", "fitnessLevel":"-"},
  {"name":"三本杭","area":"中国・四国", "altitude":"1226m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"篠山","area":"中国・四国", "altitude":"1065m", "difficulty":"★", "fitnessLevel":"-"},
  {"name":"脊振山","area":"九州", "altitude":"1055m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"鶴見岳","area":"九州", "altitude":"1375m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"涌蓋山","area":"九州", "altitude":"1500m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"大船山","area":"九州", "altitude":"1786m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"傾山","area":"九州", "altitude":"1605m", "difficulty":"★★★★", "fitnessLevel":"-"},
  {"name":"多良岳","area":"九州", "altitude":"996m", "difficulty":"★★★", "fitnessLevel":"-"},
  {"name":"国見岳","area":"九州", "altitude":"1739m", "difficulty":"★★", "fitnessLevel":"-"},
  {"name":"高隅山","area":"九州", "altitude":"1236m", "difficulty":"★★", "fitnessLevel":"-"},
]

def getMountainInfoDic():
  result = {}
  tmp = {}

  for anInfo in mountainInfos:
    name = anInfo["name"]
    if name in tmp:
      tmp[name] = tmp[name] + 1
      name = name + "_" + str(tmp[name])
      anInfo["name"] = name
    else:
      tmp[name] = 1

    if not "area" in anInfo:
      anInfo["area"] = ""
    if not "alttitude" in anInfo:
      anInfo["alttitude"] = ""
    if not "difficulty" in anInfo:
      anInfo["difficulty"] = ""
    if not "fitnessLevel" in anInfo:
      anInfo["fitnessLevel"] = ""

    result[ name ] = anInfo

  return result
