mountainInfos=[
  {"name":"", "type":"100famous"},
  {"name":"利尻岳", "area":"北海道", "altitude":"1719m", "difficulty":"★★★", "fitnessLevel":"37"},
  {"name":"羅臼岳", "area":"北海道", "altitude":"1661m", "difficulty":"★★★", "fitnessLevel":"39"},
  {"name":"斜里岳", "area":"北海道", "altitude":"1547m", "difficulty":"★★★", "fitnessLevel":"29"},
  {"name":"阿寒岳", "area":"北海道", "altitude":"1499m", "difficulty":"★★", "fitnessLevel":"27"},
  {"name":"大雪山", "area":"北海道", "altitude":"2290m", "difficulty":"★★★", "fitnessLevel":"30"},
  {"name":"トムラウシ山", "area":"北海道", "altitude":"2141m", "difficulty":"★★★", "fitnessLevel":"67"},
  {"name":"十勝岳", "area":"北海道", "altitude":"2077m", "difficulty":"★★★", "fitnessLevel":"40"},
  {"name":"幌尻岳", "area":"北海道", "altitude":"2052m", "difficulty":"★★★★", "fitnessLevel":"64"},
  {"name":"後方羊蹄山", "area":"北海道", "altitude":"1898m", "difficulty":"★★★", "fitnessLevel":"42"},
  {"name":"岩木山", "area":"東北", "altitude":"1625m", "difficulty":"★★★", "fitnessLevel":"32"},
  {"name":"八甲田山", "area":"東北", "altitude":"1585m", "difficulty":"★★", "fitnessLevel":"20"},
  {"name":"八幡平", "area":"東北", "altitude":"1613m", "difficulty":"★★", "fitnessLevel":"16"},
  {"name":"岩手山", "area":"東北", "altitude":"2038m", "difficulty":"★★★", "fitnessLevel":"37"},
  {"name":"早池峰山", "area":"東北", "altitude":"1917m", "difficulty":"★★", "fitnessLevel":"19"},
  {"name":"鳥海山", "area":"東北", "altitude":"2236m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"月山", "area":"東北", "altitude":"1980m", "difficulty":"★★", "fitnessLevel":"★"},
  {"name":"朝日連峰", "area":"東北", "altitude":"1870m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"蔵王山", "area":"東北", "altitude":"1841m", "difficulty":"★", "fitnessLevel":"★"},
  {"name":"飯豊連峰", "area":"東北", "altitude":"2105m", "difficulty":"★★★", "fitnessLevel":"★★★"},
  {"name":"吾妻山", "area":"東北", "altitude":"2035m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"安達太良山", "area":"東北", "altitude":"1700m", "difficulty":"★★", "fitnessLevel":"★"},
  {"name":"磐梯山", "area":"東北", "altitude":"1819m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"会津駒ヶ岳", "area":"東北", "altitude":"2132m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"那須岳", "area":"北関東", "altitude":"1915m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"筑波山", "area":"北関東", "altitude":"877m", "difficulty":"★", "fitnessLevel":"★"},
  {"name":"燧ヶ岳", "area":"尾瀬", "altitude":"2356m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"至仏山", "area":"尾瀬", "altitude":"2228m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"武尊山", "area":"上州", "altitude":"2158m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"赤城山", "area":"上州", "altitude":"1828m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"男体山", "area":"日光", "altitude":"2486m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"日光白根山", "area":"日光", "altitude":"2578m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"皇海山", "area":"足尾", "altitude":"2144m", "difficulty":"★★", "fitnessLevel":"★"},
  {"name":"越後駒ヶ岳", "area":"上信越", "altitude":"2003m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"平ヶ岳", "area":"上信越", "altitude":"2141m", "difficulty":"★", "fitnessLevel":"★★★"},
  {"name":"巻機山", "area":"上信越", "altitude":"1967m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"谷川岳", "area":"上信越", "altitude":"1963m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"苗場山", "area":"上信越", "altitude":"2145m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"雨飾山", "area":"上信越", "altitude":"1963m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"妙高山", "area":"上信越", "altitude":"2454m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"火打山", "area":"上信越", "altitude":"2462m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"高妻山", "area":"上信越", "altitude":"2353m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"草津白根山", "area":"上信越", "altitude":"2165m", "difficulty":"★", "fitnessLevel":"★"},
  {"name":"四阿山", "area":"上信越", "altitude":"2354m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"浅間山", "area":"上信越", "altitude":"2568m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"両神山", "area":"秩父", "altitude":"1723m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"甲武信岳", "area":"奥秩父", "altitude":"2475m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"金峰山", "area":"奥秩父", "altitude":"2595m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"瑞牆山", "area":"奥秩父", "altitude":"2230m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"雲取山", "area":"奥秩父", "altitude":"2017m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"大菩薩嶺", "area":"奥秩父", "altitude":"2057m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"丹沢", "area":"南関東", "altitude":"1567m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"富士山", "area":"南関東", "altitude":"3776m", "difficulty":"★", "fitnessLevel":"★★★"},
  {"name":"天城山", "area":"南関東", "altitude":"1406m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"白馬岳", "area":"北アルプス", "altitude":"2932m", "difficulty":"★★★", "fitnessLevel":"★★★"},
  {"name":"五竜岳", "area":"北アルプス", "altitude":"2814m", "difficulty":"★★★", "fitnessLevel":"★★★"},
  {"name":"鹿島槍ヶ岳", "area":"北アルプス", "altitude":"2890m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"剱岳", "area":"北アルプス", "altitude":"2999m", "difficulty":"★★★", "fitnessLevel":"★★★"},
  {"name":"立山", "area":"北アルプス", "altitude":"3015m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"薬師岳", "area":"北アルプス", "altitude":"2926m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"黒部五郎岳", "area":"北アルプス", "altitude":"2840m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"水晶岳", "area":"北アルプス", "altitude":"2978m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"鷲羽岳", "area":"北アルプス", "altitude":"2924m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"槍ヶ岳", "area":"北アルプス", "altitude":"3180m", "difficulty":"★★★", "fitnessLevel":"★★★"},
  {"name":"穂高岳", "area":"北アルプス", "altitude":"3190m", "difficulty":"★★★", "fitnessLevel":"★★★"},
  {"name":"常念岳", "area":"北アルプス", "altitude":"2857m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"笠ヶ岳", "area":"北アルプス", "altitude":"2897m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"焼岳", "area":"北アルプス", "altitude":"2444m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"乗鞍岳", "area":"北アルプス", "altitude":"3026m", "difficulty":"★", "fitnessLevel":"★"},
  {"name":"美ヶ原", "area":"美ヶ原", "altitude":"2034m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"霧ヶ峰", "area":"霧ヶ峰", "altitude":"1925m", "difficulty":"★", "fitnessLevel":"★"},
  {"name":"蓼科山", "area":"蓼科山", "altitude":"2530m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"八ヶ岳（赤岳）", "area":"八ヶ岳", "altitude":"2899m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"御嶽山", "area":"御嶽山", "altitude":"3067m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"木曽駒ヶ岳", "area":"中央アルプス", "altitude":"2956m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"空木岳", "area":"中央アルプス", "altitude":"2864m", "difficulty":"★★★", "fitnessLevel":"★★★"},
  {"name":"恵那山", "area":"中央アルプス", "altitude":"2191m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"甲斐駒ヶ岳", "area":"南アルプス", "altitude":"2967m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"仙丈ヶ岳", "area":"南アルプス", "altitude":"3033m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"鳳凰山", "area":"南アルプス", "altitude":"2840m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"北岳", "area":"南アルプス", "altitude":"3192m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"間ノ岳", "area":"南アルプス", "altitude":"3189m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"塩見岳", "area":"南アルプス", "altitude":"3047m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"悪沢岳", "area":"南アルプス", "altitude":"3141m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"赤石岳", "area":"南アルプス", "altitude":"3120m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"聖岳", "area":"南アルプス", "altitude":"3013m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"光岳", "area":"南アルプス", "altitude":"2591m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"白山", "area":"北陸", "altitude":"2702m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"荒島岳", "area":"北陸", "altitude":"1524m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"伊吹山", "area":"近畿", "altitude":"1377m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"大台ヶ原山", "area":"近畿", "altitude":"1695m", "difficulty":"★", "fitnessLevel":"★"},
  {"name":"大峰山", "area":"近畿", "altitude":"1915m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"大山", "area":"中国", "altitude":"1709m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"剣山", "area":"四国", "altitude":"1955m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"石鎚山", "area":"四国", "altitude":"1982m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"九重山", "area":"九州", "altitude":"1787m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"祖母山", "area":"九州", "altitude":"1756m", "difficulty":"★★", "fitnessLevel":"★★★"},
  {"name":"阿蘇山", "area":"九州", "altitude":"1592m", "difficulty":"★★", "fitnessLevel":"★★"},
  {"name":"霧島山", "area":"九州", "altitude":"1700m", "difficulty":"★", "fitnessLevel":"★★"},
  {"name":"開聞岳", "area":"九州", "altitude":"922m", "difficulty":"★", "fitnessLevel":"★"},
  {"name":"宮之浦岳", "area":"九州", "altitude":"1936m", "difficulty":"★★★", "fitnessLevel":"★★★"},

  {"name":"", "type":"300famous"},
  {"name":"ニセイカウシュッペ山","area":"北海道", "altitude":"1883m", "difficulty":"★★", "fitnessLevel":"22"},
  {"name":"オプタテシケ山","area":"北海道", "altitude":"2013m", "difficulty":"★★★★", "fitnessLevel":"44"},
  {"name":"神威岳","area":"北海道", "altitude":"1600m", "difficulty":"★★★★", "fitnessLevel":"41"},
  {"name":"余市岳","area":"北海道", "altitude":"1488m", "difficulty":"★★", "fitnessLevel":"30"},
  {"name":"ニセコアンヌプリ","area":"北海道", "altitude":"1308m", "difficulty":"★", "fitnessLevel":"14"},
  {"name":"狩場山","area":"北海道", "altitude":"1520m", "difficulty":"★★", "fitnessLevel":"22"},
  {"name":"大千軒岳","area":"北海道", "altitude":"1072m", "difficulty":"★★", "fitnessLevel":"28"},
  {"name":"五葉山","area":"東北", "altitude":"1351m", "difficulty":"★", "fitnessLevel":"17"},
  {"name":"乳頭山（烏帽子岳）","area":"東北", "altitude":"1478m", "difficulty":"★★", "fitnessLevel":"20"},
  {"name":"太平山","area":"東北", "altitude":"1170m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"泉ヶ岳","area":"東北", "altitude":"1175m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"摩耶山","area":"東北", "altitude":"1020m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"祝瓶山","area":"東北", "altitude":"1417m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"一切経山","area":"東北", "altitude":"1949m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"大滝根山","area":"東北", "altitude":"1192m", "difficulty":"★", "fitnessLevel":""},
  {"name":"二岐山","area":"東北", "altitude":"1544m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"七ヶ岳","area":"東北", "altitude":"1636m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"荒海山（太郎岳）","area":"東北", "altitude":"1581m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"八溝山","area":"関東", "altitude":"1022m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"男鹿岳","area":"関東", "altitude":"1777m", "difficulty":"★★★★", "fitnessLevel":""},
  {"name":"高原山","area":"関東", "altitude":"1795m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"太郎山","area":"関東", "altitude":"2368m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"袈裟丸山","area":"関東", "altitude":"1961m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"景鶴山","area":"関東", "altitude":"2004m", "difficulty":"登山不可", "fitnessLevel":"登山不可"},
  {"name":"朝日岳","area":"関東", "altitude":"1945m", "difficulty":"★★★★", "fitnessLevel":""},
  {"name":"諏訪山","area":"関東", "altitude":"1549m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"三頭山","area":"関東", "altitude":"1531m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"大山","area":"関東", "altitude":"1252m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"金時山","area":"関東", "altitude":"1212m", "difficulty":"★", "fitnessLevel":""},
  {"name":"箱根山（神山）","area":"関東", "altitude":"1438m", "difficulty":"★", "fitnessLevel":""},
  {"name":"金北山","area":"甲信越", "altitude":"1172m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"粟ヶ岳","area":"甲信越", "altitude":"1293m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"浅草岳","area":"甲信越", "altitude":"1585m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"米山","area":"甲信越", "altitude":"993m", "difficulty":"★", "fitnessLevel":""},
  {"name":"横手山","area":"甲信越", "altitude":"2307m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"笠ヶ岳","area":"甲信越", "altitude":"2076m", "difficulty":"★", "fitnessLevel":""},
  {"name":"斑尾山","area":"甲信越", "altitude":"1382m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"焼山","area":"甲信越", "altitude":"2400m", "difficulty":"★★★★", "fitnessLevel":""},
  {"name":"黒姫山","area":"甲信越", "altitude":"1221m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"鉢伏山","area":"甲信越", "altitude":"1929m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"入笠山","area":"甲信越", "altitude":"1955m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"国師ヶ岳","area":"甲信越", "altitude":"2592m", "difficulty":"★", "fitnessLevel":""},
  {"name":"黒岳（御坂黒岳）","area":"甲信越", "altitude":"1793m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"朝日岳","area":"北・中央アルプス", "altitude":"2418m", "difficulty":"★★★★", "fitnessLevel":""},
  {"name":"唐松岳","area":"北・中央アルプス", "altitude":"2696m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"爺ヶ岳","area":"北・中央アルプス", "altitude":"2670m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"蓮華岳","area":"北・中央アルプス", "altitude":"2799m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"鍬崎山","area":"北・中央アルプス", "altitude":"2090m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"野口五郎岳","area":"北・中央アルプス", "altitude":"2924m", "difficulty":"★★★★", "fitnessLevel":""},
  {"name":"三俣蓮華岳","area":"北・中央アルプス", "altitude":"2841m", "difficulty":"★★★★", "fitnessLevel":""},
  {"name":"鉢盛山","area":"北・中央アルプス", "altitude":"2447m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"越百山","area":"北・中央アルプス", "altitude":"2614m", "difficulty":"★★★★", "fitnessLevel":""},
  {"name":"南木曽岳","area":"北・中央アルプス", "altitude":"1679m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"奥三界岳","area":"北・中央アルプス", "altitude":"1811m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"アサヨ峰","area":"南アルプス", "altitude":"2799m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"奥茶臼山","area":"南アルプス", "altitude":"2474m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"茶臼岳","area":"南アルプス", "altitude":"2604m", "difficulty":"★★★★", "fitnessLevel":""},
  {"name":"山伏","area":"東海・北陸", "altitude":"2013m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"黒法師岳","area":"東海・北陸", "altitude":"2068m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"高塚山","area":"東海・北陸", "altitude":"1621m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"熊伏山","area":"東海・北陸", "altitude":"1654m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"白木峰","area":"東海・北陸", "altitude":"1596m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"人形山","area":"東海・北陸", "altitude":"1726m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"猿ヶ馬場山","area":"東海・北陸", "altitude":"1875m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"川上岳","area":"東海・北陸", "altitude":"1625m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"鷲ヶ岳","area":"東海・北陸", "altitude":"1671m", "difficulty":"★", "fitnessLevel":""},
  {"name":"医王山","area":"東海・北陸", "altitude":"939m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"大門山","area":"東海・北陸", "altitude":"1572m", "difficulty":"★", "fitnessLevel":""},
  {"name":"大笠山","area":"東海・北陸", "altitude":"1822m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"三方岩岳","area":"東海・北陸", "altitude":"1736m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"野伏ヶ岳","area":"東海・北陸", "altitude":"1674m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"経ヶ岳","area":"東海・北陸", "altitude":"1625m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"冠山","area":"東海・北陸", "altitude":"1257m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"藤原岳","area":"近畿", "altitude":"1140m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"倶留尊山","area":"近畿", "altitude":"1037m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"三峰山","area":"近畿", "altitude":"1235m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"高見山","area":"近畿", "altitude":"1248m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"龍門岳","area":"近畿", "altitude":"904m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"山上ヶ岳","area":"近畿", "altitude":"1719m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"護摩壇山","area":"近畿", "altitude":"1372m", "difficulty":"★", "fitnessLevel":""},
  {"name":"大和葛城山","area":"近畿", "altitude":"959m", "difficulty":"★", "fitnessLevel":""},
  {"name":"蓬莱山","area":"近畿", "altitude":"1174m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"比叡山","area":"近畿", "altitude":"848m", "difficulty":"★", "fitnessLevel":""},
  {"name":"愛宕山","area":"近畿", "altitude":"924m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"六甲山","area":"近畿", "altitude":"931m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"扇ノ山","area":"中国・四国", "altitude":"1310m", "difficulty":"★", "fitnessLevel":""},
  {"name":"那岐山","area":"中国・四国", "altitude":"1255m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"道後山","area":"中国・四国", "altitude":"1271m", "difficulty":"★", "fitnessLevel":""},
  {"name":"吾妻山","area":"中国・四国", "altitude":"1238m", "difficulty":"★", "fitnessLevel":""},
  {"name":"伊予富士","area":"中国・四国", "altitude":"1756m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"瓶ヶ森","area":"中国・四国", "altitude":"1897m", "difficulty":"★", "fitnessLevel":""},
  {"name":"三本杭","area":"中国・四国", "altitude":"1226m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"篠山","area":"中国・四国", "altitude":"1065m", "difficulty":"★", "fitnessLevel":""},
  {"name":"脊振山","area":"九州", "altitude":"1055m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"鶴見岳","area":"九州", "altitude":"1375m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"涌蓋山","area":"九州", "altitude":"1500m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"大船山","area":"九州", "altitude":"1786m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"傾山","area":"九州", "altitude":"1605m", "difficulty":"★★★★", "fitnessLevel":""},
  {"name":"多良岳","area":"九州", "altitude":"996m", "difficulty":"★★★", "fitnessLevel":""},
  {"name":"国見岳","area":"九州", "altitude":"1739m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"高隅山","area":"九州", "altitude":"1236m", "difficulty":"★★", "fitnessLevel":""},
  {"name":"高隈山","area":"九州", "altitude":"1236m", "difficulty":"★★", "fitnessLevel":""},

  {"name":"", "type":"200famous"},
  {"name":"天塩岳","area":"北海道","altitude":"1558m","difficulty":"★★","fitnessLevel":"27"},
  {"name":"石狩岳","area":"北海道","altitude":"1967m","difficulty":"★★★★","fitnessLevel":"51"},
  {"name":"ニペソツ山","area":"北海道","altitude":"2013m","difficulty":"★★★","fitnessLevel":"40"},
  {"name":"ｶﾑｲｴｸｳﾁｶｳｼ山","area":"北海道","altitude":"1979m","difficulty":"★★★★","fitnessLevel":"103"},
  {"name":"ペテガリ岳","area":"北海道","altitude":"1736m","difficulty":"★★★★","fitnessLevel":"76"},
  {"name":"芦別岳","area":"北海道","altitude":"1726m","difficulty":"★★★★","fitnessLevel":"46"},
  {"name":"夕張岳","area":"北海道","altitude":"1668m","difficulty":"★★★","fitnessLevel":"33"},
  {"name":"暑寒別岳","area":"北海道","altitude":"1492m","difficulty":"★★★","fitnessLevel":"41"},
  {"name":"樽前山","area":"北海道","altitude":"1041m","difficulty":"★","fitnessLevel":"16"},
  {"name":"北海道駒ヶ岳","area":"北海道","altitude":"1131m","difficulty":"★","fitnessLevel":"10"},
  {"name":"白神岳","area":"東北","altitude":"1235m","difficulty":"★★","fitnessLevel":"38"},
  {"name":"姫神山","area":"東北","altitude":"1124m","difficulty":"★","fitnessLevel":"14"},
  {"name":"秋田駒ヶ岳","area":"東北","altitude":"1637m","difficulty":"★★","fitnessLevel":"12"},
  {"name":"和賀岳","area":"東北","altitude":"1439m","difficulty":"★★★","fitnessLevel":"34"},
  {"name":"森吉山","area":"東北","altitude":"1454m","difficulty":"★★","fitnessLevel":"23"},
  {"name":"焼石岳","area":"東北","altitude":"1547m","difficulty":"★★","fitnessLevel":"24"},
  {"name":"栗駒山","area":"東北","altitude":"1626m","difficulty":"★★","fitnessLevel":"14"},
  {"name":"神室山","area":"東北","altitude":"1365m","difficulty":"★★★","fitnessLevel":"31"},
  {"name":"船形山","area":"東北","altitude":"1500m","difficulty":"★★","fitnessLevel":""},
  {"name":"以東岳","area":"東北","altitude":"1772m","difficulty":"★★★★","fitnessLevel":""},
  {"name":"杁差岳","area":"東北","altitude":"1636m","difficulty":"★★★","fitnessLevel":""},
  {"name":"二王子岳","area":"東北","altitude":"1420m","difficulty":"★★","fitnessLevel":""},
  {"name":"帝釈山","area":"東北","altitude":"2060m","difficulty":"★★","fitnessLevel":""},
  {"name":"会津朝日岳","area":"東北","altitude":"1624m","difficulty":"★★★","fitnessLevel":""},
  {"name":"女峰山","area":"関東","altitude":"2483m","difficulty":"★★★★","fitnessLevel":""},
  {"name":"仙ノ倉山","area":"関東","altitude":"2026m","difficulty":"★★★","fitnessLevel":""},
  {"name":"榛名山","area":"関東","altitude":"1449m","difficulty":"★","fitnessLevel":""},
  {"name":"浅間隠山","area":"関東","altitude":"1757m","difficulty":"★★","fitnessLevel":""},
  {"name":"妙義山","area":"関東","altitude":"1104m","difficulty":"★★★","fitnessLevel":""},
  {"name":"荒船山","area":"関東","altitude":"1423m","difficulty":"★","fitnessLevel":""},
  {"name":"武甲山","area":"関東","altitude":"1304m","difficulty":"★★","fitnessLevel":""},
  {"name":"白石山（和名倉山）","area":"関東","altitude":"2036m","difficulty":"★★★","fitnessLevel":""},
  {"name":"大岳山","area":"関東","altitude":"1266m","difficulty":"★★","fitnessLevel":""},
  {"name":"御神楽岳","area":"甲信越","altitude":"1386m","difficulty":"★★★★","fitnessLevel":""},
  {"name":"守門岳","area":"甲信越","altitude":"1537m","difficulty":"★★","fitnessLevel":""},
  {"name":"八海山","area":"甲信越","altitude":"1778m","difficulty":"★★★","fitnessLevel":""},
  {"name":"荒沢岳","area":"甲信越","altitude":"1969m","difficulty":"★★★","fitnessLevel":""},
  {"name":"中ノ岳","area":"甲信越","altitude":"2085m","difficulty":"★★★★","fitnessLevel":""},
  {"name":"佐武流山","area":"甲信越","altitude":"2192m","difficulty":"★★★★","fitnessLevel":""},
  {"name":"白砂山","area":"甲信越","altitude":"2140m","difficulty":"★★★","fitnessLevel":""},
  {"name":"鳥甲山","area":"甲信越","altitude":"2038m","difficulty":"★★★","fitnessLevel":""},
  {"name":"岩菅山","area":"甲信越","altitude":"2295m","difficulty":"★★","fitnessLevel":""},
  {"name":"飯縄山","area":"甲信越","altitude":"1917m","difficulty":"★★","fitnessLevel":""},
  {"name":"黒姫山","area":"甲信越","altitude":"2053m","difficulty":"★★★","fitnessLevel":""},
  {"name":"戸隠山","area":"甲信越","altitude":"1904m","difficulty":"★★★","fitnessLevel":""},
  {"name":"天狗岳","area":"甲信越","altitude":"2646m","difficulty":"★★","fitnessLevel":""},
  {"name":"御座山","area":"甲信越","altitude":"2112m","difficulty":"★★","fitnessLevel":""},
  {"name":"乾徳山","area":"甲信越","altitude":"2031m","difficulty":"★★","fitnessLevel":""},
  {"name":"茅ヶ岳","area":"甲信越","altitude":"1704m","difficulty":"★★","fitnessLevel":""},
  {"name":"御正体山","area":"甲信越","altitude":"1681m","difficulty":"★★","fitnessLevel":""},
  {"name":"三ツ峠山","area":"甲信越","altitude":"1785m","difficulty":"★★★","fitnessLevel":""},
  {"name":"毛無山","area":"甲信越","altitude":"1964m","difficulty":"★★★","fitnessLevel":""},
  {"name":"櫛形山","area":"甲信越","altitude":"2052m","difficulty":"★★","fitnessLevel":""},
  {"name":"七面山","area":"甲信越","altitude":"1989m","difficulty":"★★★","fitnessLevel":""},
  {"name":"雪倉岳","area":"北・中央アルプス","altitude":"2611m","difficulty":"★★★★","fitnessLevel":""},
  {"name":"針ノ木岳","area":"北・中央アルプス","altitude":"2821m","difficulty":"★★★","fitnessLevel":""},
  {"name":"毛勝山","area":"北・中央アルプス","altitude":"2415m","difficulty":"★★★★★","fitnessLevel":""},
  {"name":"奥大日岳","area":"北・中央アルプス","altitude":"2611m","difficulty":"★★★","fitnessLevel":""},
  {"name":"烏帽子岳","area":"北・中央アルプス","altitude":"2628m","difficulty":"★★★★","fitnessLevel":""},
  {"name":"赤牛岳","area":"北・中央アルプス","altitude":"2864m","difficulty":"★★★★","fitnessLevel":""},
  {"name":"餓鬼岳","area":"北・中央アルプス","altitude":"2647m","difficulty":"★★★","fitnessLevel":""},
  {"name":"有明山","area":"北・中央アルプス","altitude":"2268m","difficulty":"★★★","fitnessLevel":""},
  {"name":"燕岳","area":"北・中央アルプス","altitude":"2763m","difficulty":"★★★","fitnessLevel":""},
  {"name":"大天井岳","area":"北・中央アルプス","altitude":"2922m","difficulty":"★★★","fitnessLevel":""},
  {"name":"霞沢岳","area":"北・中央アルプス","altitude":"2646m","difficulty":"★★★","fitnessLevel":""},
  {"name":"経ヶ岳","area":"北・中央アルプス","altitude":"2296m","difficulty":"★★","fitnessLevel":""},
  {"name":"南駒ヶ岳","area":"北・中央アルプス","altitude":"2841m","difficulty":"★★★★","fitnessLevel":""},
  {"name":"安平路山","area":"北・中央アルプス","altitude":"2363m","difficulty":"★★★★","fitnessLevel":""},
  {"name":"小秀山","area":"北・中央アルプス","altitude":"1982m","difficulty":"★★★","fitnessLevel":""},
  {"name":"鋸岳","area":"南アルプス","altitude":"2685m","difficulty":"★★★★★","fitnessLevel":""},
  {"name":"農鳥岳","area":"南アルプス","altitude":"3026m","difficulty":"★★★★","fitnessLevel":""},
  {"name":"笊ヶ岳","area":"南アルプス","altitude":"2629m","difficulty":"★★★★","fitnessLevel":""},
  {"name":"上河内岳","area":"南アルプス","altitude":"2803m","difficulty":"★★★★","fitnessLevel":""},
  {"name":"池口岳","area":"南アルプス","altitude":"2392m","difficulty":"★★★","fitnessLevel":""},
  {"name":"大無間山","area":"南アルプス","altitude":"2330m","difficulty":"★★★★","fitnessLevel":""},
  {"name":"愛鷹山","area":"東海・北陸","altitude":"1504m","difficulty":"★★","fitnessLevel":""},
  {"name":"金剛堂山","area":"東海・北陸","altitude":"1650m","difficulty":"★★★","fitnessLevel":""},
  {"name":"位山","area":"東海・北陸","altitude":"1529m","difficulty":"★","fitnessLevel":""},
  {"name":"笈ヶ岳","area":"東海・北陸","altitude":"1841m","difficulty":"★★★★","fitnessLevel":""},
  {"name":"大日ヶ岳","area":"東海・北陸","altitude":"1709m","difficulty":"★★","fitnessLevel":""},
  {"name":"能郷白山","area":"東海・北陸","altitude":"1617m","difficulty":"★","fitnessLevel":""},
  {"name":"御在所岳","area":"近畿","altitude":"1212m","difficulty":"★★","fitnessLevel":""},
  {"name":"釈迦ヶ岳","area":"近畿","altitude":"1800m","difficulty":"★★★","fitnessLevel":""},
  {"name":"伯母子岳","area":"近畿","altitude":"1344m","difficulty":"★★","fitnessLevel":""},
  {"name":"金剛山","area":"近畿","altitude":"1125m","difficulty":"★★","fitnessLevel":""},
  {"name":"武奈ヶ岳","area":"近畿","altitude":"1214m","difficulty":"★★★","fitnessLevel":""},
  {"name":"氷ノ山","area":"中国・四国","altitude":"1510m","difficulty":"★★","fitnessLevel":""},
  {"name":"上蒜山","area":"中国・四国","altitude":"1202m","difficulty":"★★","fitnessLevel":""},
  {"name":"三瓶山","area":"中国・四国","altitude":"1126m","difficulty":"★★","fitnessLevel":""},
  {"name":"三嶺","area":"中国・四国","altitude":"1894m","difficulty":"★★★","fitnessLevel":""},
  {"name":"東赤石山","area":"中国・四国","altitude":"1706m","difficulty":"★★★","fitnessLevel":""},
  {"name":"笹ヶ峰","area":"中国・四国","altitude":"1860m","difficulty":"★★","fitnessLevel":""},
  {"name":"英彦山","area":"九州","altitude":"1199m","difficulty":"★★","fitnessLevel":""},
  {"name":"由布岳","area":"九州","altitude":"1583m","difficulty":"★★","fitnessLevel":""},
  {"name":"大崩山","area":"九州","altitude":"1644m","difficulty":"★★★★","fitnessLevel":""},
  {"name":"雲仙岳","area":"九州","altitude":"1483m","difficulty":"★★","fitnessLevel":""},
  {"name":"市房山","area":"九州","altitude":"1721m","difficulty":"★★★","fitnessLevel":""},
  {"name":"尾鈴山","area":"九州","altitude":"1405m","difficulty":"★★","fitnessLevel":""},
  {"name":"高千穂峰","area":"九州","altitude":"1574m","difficulty":"★★","fitnessLevel":""},
  {"name":"桜島","area":"九州","altitude":"1117m","difficulty":"★★","fitnessLevel":""},
]

def getNormalizedFitnessLevel(fitnessLevel):
  if fitnessLevel.isnumeric():
    theFitnessLevel = int( fitnessLevel )
    if theFitnessLevel>0:
      if theFitnessLevel>0 and theFitnessLevel<15:
        fitnessLevel = "★"
      elif theFitnessLevel>=15 and theFitnessLevel<25:
        fitnessLevel = "★★"
      elif theFitnessLevel>=25 and theFitnessLevel<35:
        fitnessLevel = "★★★"
      elif theFitnessLevel>=35 and theFitnessLevel<45:
        fitnessLevel = "★★★★"
      elif theFitnessLevel>=45:
        fitnessLevel = "★★★★★"

  return fitnessLevel

def getMountainInfoDic():
  result = {}
  tmp = {}
  type = ""

  for anInfo in mountainInfos:
    name = anInfo["name"]
    if name in tmp:
      tmp[name] = tmp[name] + 1
      name = name + "_" + str(tmp[name])
      anInfo["name"] = name
    else:
      tmp[name] = 1

    if "type" in anInfo:
      type = anInfo["type"]
    else:
      anInfo["type"] = type
    if not "area" in anInfo:
      anInfo["area"] = ""
    if not "altitude" in anInfo:
      anInfo["altitude"] = ""
    if not "difficulty" in anInfo:
      anInfo["difficulty"] = ""
    if not "fitnessLevel" in anInfo:
      anInfo["fitnessLevel"] = ""
    anInfo["fitnessLevel"] = getNormalizedFitnessLevel( anInfo["fitnessLevel"] )

    if name!="":
      result[ name ] = anInfo

      pos = name.find("<")
      if pos!=-1:
        pos2 = name.find(">")
        result[ name[pos+1:pos2] ] = anInfo
        name = name[0:pos]
      pos = name.find("(")
      if pos!=-1:
        pos2 = name.find(")")
        result[ name[pos+1:pos2] ] = anInfo
        name = name[0:pos]
      pos = name.find("（")
      if pos!=-1:
        pos2 = name.find("）")
        result[ name[pos+1:pos2] ] = anInfo
        name = name[0:pos]

      result[ name ] = anInfo

  return result
